spring:
  application:
    name: contact-management

  datasource:
    uri: jdbc:mysql://localhost:3306/contact-management
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format-sql: true
    open-in-view: false

#  mongodb:
#    database: contact-management
#    uri: mongodb://localhost:27017/contact-management

server:
  port: 9000
  servlet:
    context-path: /contact-management